### ISSUE TITLE
Minor: Uppercase & Lowercase Extensions Correctly

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen.Environment#2]
PopCap Standard when they uppercase or lowercase file extensions.

This should be applies to every functions that can generating files (like Encode, Decode, Split and Merge,...)

Include extensions: RTON, TXT, PTX, PNG, PAM, WEM, BNK, CFW2
Exclude extension: json (looks better in lowercase)

- Uppercase file extension if the file name has full uppercase alphabet characters
(example: LAWNSTRINGS-EN-US, @123456789Z)

- Uppercase file extension if the file name has none alphabet character
(example: @123456789#)

- Lowercase file extension if the file name doesn't has full uppercase characters
(example: LawnStrings-en-us, 123456789z)

**Comment by harumazzz** [comment]
Refuse to change. If you need uppercase extension go to Script/Executor/Methods/*.js and change them yourself.
