### ISSUE TITLE
QoL: Execution Status

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen.Environment#3]
Improve Quality of Life in Execution Status

- Add Sprite Count to PopCap Atlas: Merge status
- Add File Size for output files if possible
- Fix localization for PopCap RSB: Pack for Modding status: Finished -> Packing: (eg. Packing: Packages). Converted -> Converting: (eg. Converting: 69 JSONs -> RTONs), if there is 1 json only, use singular (Converting: 1 JSON -> RTON)
- Converting: JSON -> RTON should be in Execution Status, not Execution Processed)
- 0 successful 1 failed should appear when the tool show you errors

**Comment by harumazzz** [comment]
This is useless, report them only make tools process slower. I don't sacrifire Users experience for poorly performance report. I only adapt some I find necessary, the rest will not be adapted.
