### ISSUE TITLE
Feature: Smart Atlas Trimming

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen.Environment#5]
Add this feature as a config for PopCap: Atlas Merge, the config will have 3 modes:
- "?": Sen has detected the resolution you chose is redundant, select an action: 0. Keep the chosen resolution. 1. Use trimmed resolution by Sen
(If choose 0, it will merge the atlas again with the resolution you have chosen before)
- false: Sen will automatically keep the chosen resolution
- true: Sen will automatically uses trimmed resolution

**Comment by harumazzz** [comment]
Sen is designed to be auto trim (for square trim and reducer trim) by default.
- Square trim: beautify the width and height to the power of 2, but also cut the unused area.
- Reducer trim: Only cut the unused area.

If you don't need to trim you can modify Script yourself, this brings no benefits to modders in general at all, so I will close this issue.
