### ISSUE TITLE
Soundbank cannot be encoded properly

### ISSUE THREAD

**Issue by min-mozj** [Haruma-VN/Sen.Environment#8]
When I put BNK into SEN, it can decode regularly. However when I put the directory back into the SEN, it crash and and output the following logs:
[json.exception.out_of_range.403] key 'switcher' not found

After my testing, this issue only appears in soundbank with music playlist, which has the string "switcher" like this:
"switcher": {
	"is_state": false,
	"group": 691073587,
	"default_item": 2617516519,
	"association": []
},

**Comment by harumazzz** [comment]
This bug is already fixed, the build is in my server.
